#include "../Sources/SchedulerCore/PostgresSchedulerRepository.hpp"

#include <cassert>
#include <optional>
#include <pqxx/pqxx>
#include <string>

int main(int argc, char* argv[])
{
    assert(argc == 2);
    using namespace EA::SchedulerCore;

    pqxx::connection connection{argv[1]};
    pqxx::work transaction{connection};
    transaction.exec(R"SQL(
        CREATE TABLE experiment_global_control(
            singleton boolean PRIMARY KEY,
            active_request_id bigint
        );
        INSERT INTO experiment_global_control VALUES(true, 77);
        CREATE TABLE experiment(
            experiment_id bigint PRIMARY KEY,
            symbol text NOT NULL,
            prediction_horizon integer NOT NULL,
            c_next_threshold double precision NOT NULL,
            core_lr_mult double precision,
            head_lr_mult double precision,
            target_epochs integer NOT NULL,
            checkpoint_interval integer NOT NULL,
            train_start timestamptz NOT NULL,
            train_end timestamptz NOT NULL,
            infer_start timestamptz,
            infer_end timestamptz,
            last_model_id bigint,
            resume_model_id bigint,
            train_log_path text,
            infer_log_path text,
            analysis_log_path text,
            donchian20_mode text NOT NULL,
            feature_warmup_scope text NOT NULL,
            donchian_lookback text NOT NULL,
            feature_ablation_mask text NOT NULL,
            fresh_initialization_seed bigint NOT NULL DEFAULT 42,
            resume_expand_input_width boolean NOT NULL,
            training_objective_canonical text NOT NULL,
            training_objective_hash text NOT NULL,
            scheduler_priority text NOT NULL DEFAULT 'normal',
            resume_requested boolean NOT NULL DEFAULT false,
            scheduler_resume_origin text NOT NULL DEFAULT 'none',
            active_scheduler_worker_attempt_id bigint,
            cancellation_request_id bigint,
            cancel_after_checkpoint_epoch integer,
            status text NOT NULL,
            phase text NOT NULL,
            worker_pid integer,
            worker_process_group_id integer,
            worker_process_start_identity text,
            worker_executable text,
            worker_command_line text,
            current_epoch integer,
            started_at timestamptz,
            worker_started_at timestamptz,
            current_operation text,
            worker_control_state text,
            worker_global_pause_request_id bigint,
            operator_forced_final_inference_rerun_requested boolean NOT NULL DEFAULT false,
            checkpoint_policy_enabled boolean NOT NULL DEFAULT false,
            checkpoint_policy_min_leader_score double precision,
            checkpoint_policy_min_infer_accuracy double precision,
            checkpoint_policy_top_n integer,
            checkpoint_policy_scope text NOT NULL DEFAULT 'symbol_horizon',
            checkpoint_policy_stop_mode text NOT NULL DEFAULT 'next_checkpoint',
            checkpoint_policy_grace_evals integer NOT NULL DEFAULT 1,
            checkpoint_infer_enabled boolean NOT NULL DEFAULT false,
            opportunistic_checkpoint_infer boolean NOT NULL DEFAULT false,
            checkpoint_policy_revision bigint NOT NULL DEFAULT 1,
            checkpoint_policy_hash text,
            checkpoint_policy_last_decision text,
            checkpoint_policy_last_decision_at timestamptz,
            checkpoint_policy_last_checkpoint_eval_id bigint,
            checkpoint_policy_last_reason text,
            checkpoint_policy_last_decision_id bigint,
            checkpoint_policy_stop_decision_id bigint,
            stop_after_checkpoint_epoch integer,
            updated_at timestamptz NOT NULL,
            completed_at timestamptz,
            exit_code integer,
            error_message text
        );
        CREATE TABLE experiment_checkpoint_eval(
            checkpoint_eval_id bigint PRIMARY KEY,
            experiment_id bigint,
            parent_experiment_id bigint,
            checkpoint_epoch integer,
            checkpoint_model_id bigint,
            status text NOT NULL,
            phase text NOT NULL,
            worker_pid integer,
            worker_process_group_id integer,
            worker_process_start_identity text,
            worker_executable text,
            worker_command_line text,
            active_scheduler_worker_attempt_id bigint,
            infer_log_path text,
            worker_control_state text,
            started_at timestamptz,
            infer_started_at timestamptz,
            analyze_started_at timestamptz,
            analyze_completed_at timestamptz,
            analysis_id bigint,
            completed_at timestamptz,
            error_message text,
            updated_at timestamptz
        );
        CREATE TABLE experiment_scheduler_worker_attempt(
            worker_attempt_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            launch_attempt_identity text,
            scheduler_invocation_id text,
            scheduler_fencing_token bigint,
            experiment_id bigint,
            checkpoint_eval_id bigint,
            worker_kind text,
            lifecycle_phase text,
            capacity_class text,
            ownership_origin text,
            lifecycle_state text NOT NULL,
            worker_pid integer,
            worker_process_group_id integer,
            worker_process_start_identity text,
            canonical_executable_path text,
            semantic_layout_version integer,
            model_input_width integer,
            semantic_worker_role text,
            source_commit text,
            executable_sha256 text,
            runtime_identity text,
            canonical_manifest_path text,
            command_identity text,
            command_line text,
            log_path text,
            reserved_at timestamptz NOT NULL DEFAULT clock_timestamp(),
            spawned_at timestamptz,
            last_observed_at timestamptz,
            completed_at timestamptz,
            exit_code integer,
            reconciliation_result text,
            diagnostic text
        );
        CREATE TABLE experiment_analysis_result(
            analysis_id bigint PRIMARY KEY,
            experiment_id bigint NOT NULL,
            model_id bigint NOT NULL,
            symbol text NOT NULL,
            prediction_horizon integer NOT NULL,
            completed_epochs integer,
            infer_accuracy double precision,
            leader_score double precision,
            analysis_scope text NOT NULL,
            analysis_status text NOT NULL,
            checkpoint_eval_id bigint,
            checkpoint_epoch integer,
            parent_experiment_id bigint
        );
        CREATE TABLE inference_eval_result(
            id bigint PRIMARY KEY,
            checkpoint_eval_id bigint,
            inference_scope text NOT NULL,
            status text NOT NULL,
            parent_experiment_id bigint,
            model_id bigint NOT NULL,
            checkpoint_epoch integer,
            symbol text NOT NULL,
            prediction_horizon integer NOT NULL,
            threshold_logret double precision NOT NULL,
            from_date text NOT NULL,
            to_date text NOT NULL,
            accuracy double precision,
            completed_at timestamptz
        );
        CREATE TABLE experiment_checkpoint_decision(
            checkpoint_decision_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            checkpoint_eval_id bigint NOT NULL,
            parent_experiment_id bigint NOT NULL,
            checkpoint_epoch integer NOT NULL,
            checkpoint_model_id bigint NOT NULL,
            analysis_id bigint NOT NULL,
            inference_eval_result_id bigint NOT NULL,
            policy_revision bigint,
            policy_hash text,
            evidence_watermark text,
            rank_population_watermark text,
            identity_status text NOT NULL,
            superseded_at timestamptz,
            superseded_reason text,
            superseded_by_decision_id bigint,
            decision text NOT NULL,
            reason text NOT NULL,
            leader_score double precision,
            infer_accuracy double precision,
            rank_value integer,
            rank_scope text NOT NULL,
            requested_stop_epoch integer,
            stop_request_applied boolean NOT NULL DEFAULT false,
            stop_request_applied_at timestamptz,
            stop_action_worker_attempt_id bigint,
            created_at timestamptz NOT NULL DEFAULT clock_timestamp()
        );
        CREATE UNIQUE INDEX checkpoint_decision_identity_test
        ON experiment_checkpoint_decision(
            checkpoint_eval_id,policy_revision,policy_hash,evidence_watermark
        ) WHERE policy_revision IS NOT NULL AND policy_hash IS NOT NULL
            AND evidence_watermark IS NOT NULL;
        CREATE TABLE experiment_scheduler_protocol(
            singleton boolean PRIMARY KEY,
            required_generation integer NOT NULL,
            cutover_state text NOT NULL,
            failure_diagnostic text,
            cutover_completed_at timestamptz,
            cutover_completed_by text,
            cutover_executable_path text,
            cutover_process_evidence text,
            updated_at timestamptz
        );
        INSERT INTO experiment_scheduler_protocol(
            singleton,required_generation,cutover_state,updated_at
        ) VALUES(true,52,'complete',clock_timestamp());
        CREATE TABLE experiment_scheduler_invocation(
            scheduler_invocation_id text PRIMARY KEY,
            process_pid integer NOT NULL,
            process_group_id integer NOT NULL,
            process_start_identity text NOT NULL,
            canonical_executable_path text NOT NULL,
            command_line text NOT NULL,
            invocation_nonce text NOT NULL,
            status text NOT NULL,
            protocol_generation integer NOT NULL,
            ownership_acquired_at timestamptz,
            ownership_released_at timestamptz,
            last_heartbeat_at timestamptz,
            ended_at timestamptz,
            terminal_reason text
        );
        CREATE TABLE experiment_scheduler_lease(
            singleton boolean PRIMARY KEY,
            owner_scheduler_invocation_id text,
            fencing_token bigint NOT NULL,
            authority_state text NOT NULL,
            acquired_at timestamptz,
            heartbeat_at timestamptz,
            expires_at timestamptz,
            released_at timestamptz,
            transition_reason text
        );
        INSERT INTO experiment_scheduler_lease(
            singleton,fencing_token,authority_state,expires_at
        ) VALUES(true,8,'vacant',clock_timestamp());
    )SQL");

    transaction.exec(R"SQL(
        INSERT INTO experiment(
            experiment_id,symbol,prediction_horizon,c_next_threshold,
            core_lr_mult,head_lr_mult,target_epochs,checkpoint_interval,
            train_start,train_end,infer_start,infer_end,last_model_id,
            resume_model_id,train_log_path,infer_log_path,analysis_log_path,
            donchian20_mode,feature_warmup_scope,donchian_lookback,
            feature_ablation_mask,fresh_initialization_seed,resume_expand_input_width,
            training_objective_canonical,training_objective_hash,
            scheduler_priority,resume_requested,scheduler_resume_origin,
            status,phase,updated_at
        ) VALUES
        (1,'normalpreempt',4,0.1,NULL,2.5,20,10,'2020-01-01','2021-01-01',
         NULL,'2022-01-01',NULL,88,NULL,'infer.log',NULL,
         'enabled','full_history_warmup','20','none',43,false,'objective','hash',
         'normal',true,'preemption','pending','train','2026-01-01 00:00:00+00'),
        (2,'highnone',4,0.1,1.0,1.0,20,10,'2020-01-01','2021-01-01',
         '2021-01-01','2022-01-01',10,NULL,'train.log',NULL,'analysis.log',
         'enabled','full_history_warmup','20','none',42,false,'objective','hash',
         'high',false,'none','pending','train','2026-01-01 00:00:02+00'),
        (3,'normaloperatorlater',4,0.1,1.0,1.0,20,10,'2020-01-01','2021-01-01',
         NULL,NULL,NULL,NULL,NULL,NULL,NULL,'enabled','full_history_warmup','20','none',
         42,false,'objective','hash','normal',true,'operator','pending','train',
         '2026-01-01 00:00:02+00'),
        (4,'normaloperatorearlier',4,0.1,1.0,1.0,20,10,'2020-01-01','2021-01-01',
         NULL,NULL,NULL,NULL,NULL,NULL,NULL,'enabled','full_history_warmup','20','none',
         42,false,'objective','hash','normal',true,'operator','pending','train',
         '2026-01-01 00:00:01+00'),
        (5,'lowoperator',4,0.1,1.0,1.0,20,10,'2020-01-01','2021-01-01',
         NULL,NULL,NULL,NULL,NULL,NULL,NULL,'enabled','full_history_warmup','20','none',
         42,false,'objective','hash','low',true,'operator','pending','train',
         '2025-01-01 00:00:00+00'),
        (10,'running',4,0.1,NULL,NULL,20,10,'2020-01-01','2021-01-01',
         NULL,NULL,NULL,NULL,NULL,NULL,NULL,'enabled','full_history_warmup','20',
         'none',42,false,'objective','hash','normal',false,'none','running','train',
         '2026-01-02 00:00:00+00'),
        (20,'reserveexperiment',4,0.1,1.0,1.0,20,10,
         '2020-01-01','2021-01-01',NULL,NULL,NULL,NULL,NULL,NULL,NULL,
         'enabled','full_history_warmup','20','none',42,false,'objective','hash',
         'normal',false,'none','pending','analyze',clock_timestamp()),
        (21,'reservecancellation',4,0.1,1.0,1.0,20,10,
         '2020-01-01','2021-01-01',NULL,NULL,NULL,NULL,NULL,NULL,NULL,
         'enabled','full_history_warmup','20','none',42,false,'objective','hash',
         'normal',false,'none','pending','train',clock_timestamp());
        UPDATE experiment SET cancellation_request_id=77,
            cancel_after_checkpoint_epoch=10 WHERE experiment_id=21;
        UPDATE experiment SET active_scheduler_worker_attempt_id=101
        WHERE experiment_id=10;
        INSERT INTO experiment_scheduler_worker_attempt(
            worker_attempt_id,scheduler_invocation_id,
            scheduler_fencing_token,experiment_id,checkpoint_eval_id,
            worker_kind,lifecycle_phase,capacity_class,ownership_origin,
            lifecycle_state,canonical_executable_path
        ) VALUES
            (101,'scheduler-a',7,NULL,NULL,NULL,NULL,NULL,NULL,'reserved',
             '/tmp/LSTM_Release'),
            (102,'scheduler-a',7,NULL,NULL,NULL,NULL,NULL,NULL,'reserved',
             '/tmp/LSTM_Release'),
            (103,'scheduler-a',7,NULL,NULL,NULL,NULL,NULL,NULL,'reserved',
             '/tmp/LSTM_Release'),
            (201,'scheduler-a',7,NULL,NULL,NULL,NULL,NULL,NULL,'reserved',
             '/tmp/LSTM_Release'),
            (204,'scheduler-a',7,20,204,'checkpoint_analyze','analyze',
             'analyze','scheduler_in_process','running','/tmp/LSTM_Release');
        INSERT INTO experiment_checkpoint_eval(
            checkpoint_eval_id,experiment_id,parent_experiment_id,
            checkpoint_epoch,checkpoint_model_id,status,phase,
            active_scheduler_worker_attempt_id,updated_at
        ) VALUES
            (201,20,20,10,700,'running','infer',201,clock_timestamp()),
            (202,20,20,20,701,'pending','infer',NULL,clock_timestamp()),
            (203,20,20,30,702,'pending','analyze',NULL,clock_timestamp()),
            (204,20,20,40,703,'running','analyze',204,clock_timestamp());
    )SQL");

    transaction.exec(R"SQL(
        UPDATE experiment SET
            target_epochs=100,
            infer_start='2025-01-01',
            infer_end='2025-02-01',
            checkpoint_policy_enabled=true,
            checkpoint_policy_min_leader_score=0.75,
            checkpoint_infer_enabled=true,
            current_epoch=20
        WHERE experiment_id=10;
        INSERT INTO experiment_checkpoint_eval(
            checkpoint_eval_id,experiment_id,parent_experiment_id,
            checkpoint_epoch,checkpoint_model_id,status,phase,analysis_id,
            updated_at
        ) VALUES(
            205,10,10,20,704,'completed','done',501,clock_timestamp()
        );
        INSERT INTO experiment_analysis_result(
            analysis_id,experiment_id,model_id,symbol,prediction_horizon,
            completed_epochs,infer_accuracy,leader_score,analysis_scope,
            analysis_status,checkpoint_eval_id,checkpoint_epoch,
            parent_experiment_id
        ) VALUES(
            501,10,704,'running',4,20,0.70,0.80,'checkpoint',
            'completed',205,20,10
        );
        INSERT INTO inference_eval_result(
            id,checkpoint_eval_id,inference_scope,status,parent_experiment_id,
            model_id,checkpoint_epoch,symbol,prediction_horizon,
            threshold_logret,from_date,to_date,accuracy
        ) VALUES(
            601,205,'checkpoint','completed',10,704,20,'running',4,
            0.1,'2025-01-01','2025-02-01',0.70
        );
    )SQL");

    PostgresSchedulerRepository repository{transaction};
    assert(repository.checkpointPolicySchemaAvailable());
    const CheckpointEvaluationRecord policyEvaluation{
        205, 10, 704, 20, "running", 4};
    auto policy = repository.loadCheckpointPolicyForEvaluation(10);
    assert(policy && policy->enabled && policy->checkpointInferEnabled);
    assert(policy->minLeaderScore == 0.75);
    assert(!policy->persistedPolicyHash);
    *policy = repository.reconcileCheckpointPolicyIdentity(
        policyEvaluation, *policy);
    assert(policy->persistedPolicyHash ==
           EA::ExperimentScheduler::CheckpointPolicySemanticHash(*policy));
    const auto policyEvidence =
        repository.loadCheckpointPolicyEvidence(policyEvaluation);
    assert(policyEvidence.evidence);
    assert(policyEvidence.evidence->analysisId == 501);
    assert(policyEvidence.evidence->inferenceEvalResultId == 601);
    assert(policyEvidence.evidence->leaderScore == 0.80);
    assert(policyEvidence.evidence->inferenceAccuracy == 0.70);
    const auto completedPopulation =
        repository.loadCompletedCheckpointPolicyPopulation(10);
    const auto rankPopulation =
        repository.loadCheckpointPolicyRankPopulation(
            policyEvaluation, *policy);
    assert(completedPopulation.count == 1);
    assert(rankPopulation.count == 1 && rankPopulation.rankValue == 1);
    const auto policyContext = PlanCheckpointPolicyDecision(
        policyEvaluation,
        *policy,
        *policyEvidence.evidence,
        completedPopulation,
        rankPopulation);
    const auto policyIdentity = MakeCheckpointPolicyEvidenceIdentity(
        policyEvaluation,
        *policyEvidence.evidence,
        policyContext,
        *policy);
    const auto persistedPolicyDecision =
        repository.persistCheckpointPolicyDecision(
            policyEvaluation,
            *policy,
            policyContext.decision,
            *policyEvidence.evidence,
            policyIdentity);
    assert(persistedPolicyDecision.decisionId > 0);
    assert(persistedPolicyDecision.identityStatus == "active");
    assert(!persistedPolicyDecision.reused);
    const auto repeatedPolicyDecision =
        repository.persistCheckpointPolicyDecision(
            policyEvaluation,
            *policy,
            policyContext.decision,
            *policyEvidence.evidence,
            policyIdentity);
    assert(repeatedPolicyDecision.decisionId ==
           persistedPolicyDecision.decisionId);
    assert(repeatedPolicyDecision.reused);
    assert(transaction.exec(
               "SELECT count(*) FROM experiment_checkpoint_decision "
               "WHERE checkpoint_eval_id=205;").one_row()[0].as<int>() == 1);

    const auto pending = repository.loadPendingExperiments("train", false);
    assert(pending.size() == 6);
    assert(pending[0].experiment.experimentId == 2);
    assert(pending[1].experiment.experimentId == 4);
    assert(pending[2].experiment.experimentId == 3);
    assert(pending[3].experiment.experimentId == 1);
    assert(pending[4].experiment.experimentId == 21);
    assert(pending[5].experiment.experimentId == 5);
    const auto& nullRecord = pending[3].experiment;
    assert(!nullRecord.coreLrMult);
    assert(nullRecord.headLrMult == 2.5);
    assert(!nullRecord.inferStart);
    assert(nullRecord.inferEnd.has_value());
    assert(!nullRecord.lastModelId);
    assert(nullRecord.resumeModelId == 88);
    assert(!nullRecord.trainLogPath);
    assert(nullRecord.inferLogPath == "infer.log");
    assert(!nullRecord.analysisLogPath);
    assert(nullRecord.freshInitializationSeed == 43U);
    assert(!pending[3].activeWorkerAttemptId);

    const auto experimentReservation =
        repository.reserveExperimentWorkerAttempt({
            "scheduler-a:worker:nonce:experiment:20:analyze",
            "scheduler-a",
            7,
            20,
            "analyze",
            "/tmp/LSTM_Release",
            0,
            0,
            "",
            "",
            "",
            "",
            "",
            "experiment:20:analyze",
            "analyze",
            "/tmp/analyze.log",
            false});
    assert(experimentReservation.status ==
           WorkerAttemptReservationStatus::Reserved);
    assert(experimentReservation.attempt);
    assert(experimentReservation.attempt->workerKind == "experiment");
    assert(experimentReservation.attempt->phase == "analyze");
    assert(experimentReservation.attempt->canonicalExecutablePath ==
           "/tmp/LSTM_Release");
    const pqxx::row reservedAttempt = transaction.exec(
        "SELECT semantic_layout_version,model_input_width,semantic_worker_role,"
        "source_commit,executable_sha256,runtime_identity,canonical_manifest_path "
        "FROM experiment_scheduler_worker_attempt WHERE worker_attempt_id=$1",
        pqxx::params{experimentReservation.attempt->workerAttemptId}).one_row();
    for (const auto& field : reservedAttempt)
        assert(field.is_null());
    const pqxx::row reservedExperiment = transaction.exec(
        "SELECT status,phase,current_operation,worker_control_state,"
        "active_scheduler_worker_attempt_id,analysis_log_path "
        "FROM experiment WHERE experiment_id=20").one_row();
    assert(reservedExperiment[0].as<std::string>() == "running");
    assert(reservedExperiment[1].as<std::string>() == "analyze");
    assert(reservedExperiment[2].as<std::string>() == "analyze");
    assert(reservedExperiment[3].as<std::string>() == "running");
    assert(reservedExperiment[4].as<long long>() ==
           experimentReservation.attempt->workerAttemptId);
    assert(reservedExperiment[5].as<std::string>() == "/tmp/analyze.log");

    const auto cancellationReservation =
        repository.reserveExperimentWorkerAttempt({
            "scheduler-a:worker:nonce:experiment:21:train",
            "scheduler-a",
            7,
            21,
            "train",
            "/tmp/LSTM_Release",
            8,
            64,
            "train",
            "3b44080010c1c7eb3388c637bbf6dccc98ee35b1",
            "387a05120862f21911f626901075e920965d529f49d50b158c1509932e958632",
            "abababababababababababababababababababababababababababababababab",
            "/fixtures/layout8/train.manifest",
            "experiment:21:train",
            "train",
            "/tmp/cancellation.log",
            true});
    assert(cancellationReservation.status ==
           WorkerAttemptReservationStatus::Reserved);
    const pqxx::row reservedTrainAttempt = transaction.exec(
        "SELECT semantic_layout_version,model_input_width,semantic_worker_role,"
        "source_commit,executable_sha256,runtime_identity,canonical_manifest_path "
        "FROM experiment_scheduler_worker_attempt WHERE worker_attempt_id=$1",
        pqxx::params{cancellationReservation.attempt->workerAttemptId}).one_row();
    for (const auto& field : reservedTrainAttempt)
        assert(!field.is_null());

    const auto checkpointReservation =
        repository.reserveCheckpointWorkerAttempt({
            "scheduler-a:worker:nonce:checkpoint_infer:202",
            "scheduler-a",
            7,
            20,
            202,
            "/tmp/LSTM_Release",
            0,
            0,
            "",
            "",
            "",
            "",
            "",
            "checkpoint_infer:202",
            "/tmp/checkpoint.log"});
    assert(checkpointReservation.status ==
           WorkerAttemptReservationStatus::Reserved);
    assert(checkpointReservation.attempt);
    assert(checkpointReservation.attempt->checkpointEvalId == 202);
    assert(checkpointReservation.attempt->canonicalExecutablePath ==
           "/tmp/LSTM_Release");
    const pqxx::row reservedCheckpoint = transaction.exec(
        "SELECT status,phase,worker_control_state,"
        "active_scheduler_worker_attempt_id,infer_log_path "
        "FROM experiment_checkpoint_eval WHERE checkpoint_eval_id=202")
        .one_row();
    assert(reservedCheckpoint[0].as<std::string>() == "running");
    assert(reservedCheckpoint[1].as<std::string>() == "infer");
    assert(reservedCheckpoint[2].as<std::string>() == "running");
    assert(reservedCheckpoint[3].as<long long>() ==
           checkpointReservation.attempt->workerAttemptId);
    assert(reservedCheckpoint[4].as<std::string>() == "/tmp/checkpoint.log");

    const auto checkpointAnalysis =
        repository.reserveCheckpointAnalysisAttempt({
            "scheduler-a:worker:nonce:checkpoint_analyze:203",
            "scheduler-a",
            7,
            20,
            203,
            "/tmp/LSTM_Release",
            "/tmp/LSTM_Release --schedule-experiments",
            "checkpoint_analyze:203",
            true});
    assert(checkpointAnalysis.status ==
           WorkerAttemptReservationStatus::Reserved);
    assert(checkpointAnalysis.attempt);
    assert(checkpointAnalysis.attempt->workerKind == "checkpoint_analyze");
    assert(checkpointAnalysis.attempt->checkpointEvalId == 203);
    const long long checkpointAnalysisAttemptId =
        checkpointAnalysis.attempt->workerAttemptId;
    const pqxx::row claimedAnalysis = transaction.exec(
        "SELECT status,phase,active_scheduler_worker_attempt_id,"
        "worker_pid,worker_executable,worker_command_line,"
        "analyze_started_at IS NOT NULL "
        "FROM experiment_checkpoint_eval WHERE checkpoint_eval_id=203")
        .one_row();
    assert(claimedAnalysis[0].as<std::string>() == "running");
    assert(claimedAnalysis[1].as<std::string>() == "analyze");
    assert(claimedAnalysis[2].as<long long>() == checkpointAnalysisAttemptId);
    assert(claimedAnalysis[3].is_null());
    assert(claimedAnalysis[4].as<std::string>() == "/tmp/LSTM_Release");
    assert(claimedAnalysis[5].as<std::string>() ==
           "/tmp/LSTM_Release --schedule-experiments");
    assert(claimedAnalysis[6].as<bool>());

    assert(!repository.persistCheckpointAnalysisCompletion(
        {203, checkpointAnalysisAttemptId + 1, 777, true}));
    assert(repository.persistCheckpointAnalysisCompletion(
        {203, checkpointAnalysisAttemptId, 777, true}));
    assert(repository.persistCheckpointAnalysisTerminalState({
               checkpointAnalysisAttemptId,
               "scheduler-a",
               7,
               203,
               true,
               "completed",
               "checkpoint_analysis_completed",
               "result_persisted_exactly_once"}) ==
           CheckpointAnalysisPersistenceResult::Updated);
    const pqxx::row completedAnalysis = transaction.exec(
        "SELECT status,phase,analysis_id,analyze_completed_at IS NOT NULL,"
        "active_scheduler_worker_attempt_id "
        "FROM experiment_checkpoint_eval WHERE checkpoint_eval_id=203")
        .one_row();
    assert(completedAnalysis[0].as<std::string>() == "completed");
    assert(completedAnalysis[1].as<std::string>() == "done");
    assert(completedAnalysis[2].as<long long>() == 777);
    assert(completedAnalysis[3].as<bool>());
    assert(completedAnalysis[4].is_null());

    assert(repository.persistCheckpointAnalysisTerminalState({
               204,
               "scheduler-a",
               8,
               204,
               false,
               "failed",
               "checkpoint_analysis_failed",
               "wrong_fence"}) ==
           CheckpointAnalysisPersistenceResult::
               AttemptPreconditionRejected);
    assert(repository.persistCheckpointAnalysisTerminalState({
               204,
               "scheduler-a",
               7,
               204,
               false,
               "failed",
               "checkpoint_analysis_failed",
               "missing_completed_checkpoint_inference"}) ==
           CheckpointAnalysisPersistenceResult::Updated);
    const pqxx::row failedAnalysis = transaction.exec(
        "SELECT status,phase,error_message,"
        "active_scheduler_worker_attempt_id "
        "FROM experiment_checkpoint_eval WHERE checkpoint_eval_id=204")
        .one_row();
    assert(failedAnalysis[0].as<std::string>() == "failed");
    assert(failedAnalysis[1].as<std::string>() == "analyze");
    assert(failedAnalysis[2].as<std::string>() ==
           "missing_completed_checkpoint_inference");
    assert(failedAnalysis[3].is_null());

    const auto running = repository.loadRunningExperiments();
    assert(running.size() == 3);
    assert(running[0].experiment.experimentId == 10);
    assert(!running[0].workerPid);
    const auto queue = repository.loadQueueSnapshot();
    assert(queue.pendingTrain == 5);
    assert(queue.runningTrain == 2);
    assert(queue.pendingInfer == 0 && queue.runningInfer == 0);
    assert(queue.runningAnalyze == 1);

    const SpawnedWorkerAttemptUpdate spawned{
        101,
        "scheduler-a",
        7,
        10,
        std::nullopt,
        "train",
        43210,
        "start-identity",
        "/tmp/LSTM_Release",
        "/tmp/LSTM_Release --train"};
    assert(repository.persistSpawnedWorkerAttempt(spawned) ==
           SpawnPersistenceResult::Updated);
    SpawnedWorkerAttemptUpdate substitutedExecutable = spawned;
    substitutedExecutable.canonicalExecutablePath = "/tmp/other_worker";
    assert(repository.persistSpawnedWorkerAttempt(substitutedExecutable) ==
           SpawnPersistenceResult::AttemptPreconditionRejected);
    const pqxx::row mapped = transaction.exec(
        "SELECT a.lifecycle_state,a.worker_pid,a.worker_process_group_id,"
        "a.worker_process_start_identity,a.canonical_executable_path,"
        "a.command_line,e.worker_pid,e.worker_process_group_id,"
        "e.worker_process_start_identity,e.worker_executable,e.worker_command_line "
        "FROM experiment_scheduler_worker_attempt a CROSS JOIN experiment e "
        "WHERE a.worker_attempt_id=101 AND e.experiment_id=10").one_row();
    assert(mapped[0].as<std::string>() == "spawned");
    assert(mapped[1].as<int>() == 43210 && mapped[2].as<int>() == 43210);
    assert(mapped[3].as<std::string>() == "start-identity");
    assert(mapped[4].as<std::string>() == "/tmp/LSTM_Release");
    assert(mapped[5].as<std::string>() == "/tmp/LSTM_Release --train");
    assert(mapped[6].as<int>() == 43210 && mapped[7].as<int>() == 43210);
    assert(mapped[8].as<std::string>() == "start-identity");
    assert(mapped[9].as<std::string>() == "/tmp/LSTM_Release");
    assert(mapped[10].as<std::string>() == "/tmp/LSTM_Release --train");

    SpawnedWorkerAttemptUpdate wrongFence = spawned;
    wrongFence.workerAttemptId = 102;
    wrongFence.schedulerFencingToken = 8;
    assert(repository.persistSpawnedWorkerAttempt(wrongFence) ==
           SpawnPersistenceResult::AttemptPreconditionRejected);

    SpawnedWorkerAttemptUpdate checkpointSpawn = spawned;
    checkpointSpawn.workerAttemptId = 201;
    checkpointSpawn.experimentId = 11;
    checkpointSpawn.checkpointEvalId = 201;
    checkpointSpawn.phase = "infer";
    checkpointSpawn.workerPid = 43211;
    checkpointSpawn.commandLine = "/tmp/LSTM_Release --infer";
    assert(repository.persistSpawnedWorkerAttempt(checkpointSpawn) ==
           SpawnPersistenceResult::Updated);
    const pqxx::row checkpointMapped = transaction.exec(
        "SELECT worker_pid,worker_process_group_id,"
        "worker_process_start_identity,worker_executable,worker_command_line "
        "FROM experiment_checkpoint_eval WHERE checkpoint_eval_id=201")
        .one_row();
    assert(checkpointMapped[0].as<int>() == 43211);
    assert(checkpointMapped[1].as<int>() == 43211);
    assert(checkpointMapped[2].as<std::string>() == "start-identity");
    assert(checkpointMapped[3].as<std::string>() == "/tmp/LSTM_Release");
    assert(checkpointMapped[4].as<std::string>() ==
           "/tmp/LSTM_Release --infer");

    transaction.exec(
        "UPDATE experiment SET active_scheduler_worker_attempt_id=103,"
        "worker_pid=NULL,worker_process_group_id=NULL WHERE experiment_id=10;");
    assert(repository.persistWorkerAttemptLaunchFailure({
               103,
               "scheduler-a",
               7,
               10,
               std::nullopt,
               "train",
               127,
               "launch_failed_errno_2"}) ==
           LaunchFailurePersistenceResult::Updated);
    const pqxx::row failed = transaction.exec(
        "SELECT a.lifecycle_state,a.reconciliation_result,a.exit_code,"
        "e.status,e.active_scheduler_worker_attempt_id,e.error_message "
        "FROM experiment_scheduler_worker_attempt a CROSS JOIN experiment e "
        "WHERE a.worker_attempt_id=103 AND e.experiment_id=10").one_row();
    assert(failed[0].as<std::string>() == "launch_failed");
    assert(failed[1].as<std::string>() == "launch_failed");
    assert(failed[2].as<int>() == 127);
    assert(failed[3].as<std::string>() == "failed");
    assert(failed[4].is_null());
    assert(failed[5].as<std::string>() == "launch_failed_errno_2");

    repository.acquireAuthorityCoordinationLock();
    const auto protocol = repository.loadSchedulerProtocolForUpdate();
    assert(protocol && protocol->requiredGeneration == 52);
    assert(protocol->cutoverState == "complete");
    repository.registerSchedulerInvocation({
        "scheduler-repository-test",
        900,
        900,
        "scheduler-start",
        "/tmp/LSTM_Release",
        "/tmp/LSTM_Release --schedule-experiments",
        "repository-test-nonce",
        52});
    const auto lease = repository.loadSchedulerLeaseForUpdate();
    assert(lease && !lease->ownerSchedulerInvocationId);
    assert(lease->fencingToken == 8 && lease->authorityState == "vacant");
    assert(repository.acquireSchedulerLease({
        "scheduler-repository-test", 9, 90, "vacant"}));
    repository.markSchedulerInvocationOwner("scheduler-repository-test");
    const SchedulerAuthorityIdentity authority{
        "scheduler-repository-test", 9};
    assert(repository.renewSchedulerLease(authority, 90));
    repository.touchSchedulerInvocation("scheduler-repository-test");
    assert(!repository.renewSchedulerLease(
        {"scheduler-repository-test", 10}, 90));
    assert(repository.displaceSchedulerAuthorityForTest(
        authority, "scheduler-foreign", "test_failpoint:repository", 90));
    assert(!repository.releaseSchedulerLease(authority, "stale_release"));
    const SchedulerAuthorityIdentity foreign{"scheduler-foreign", 10};
    assert(repository.releaseSchedulerLease(foreign, "scheduler_exit"));

    transaction.exec(
        "UPDATE experiment_scheduler_protocol SET cutover_state='pending' "
        "WHERE singleton=true;");
    assert(repository.completeSchedulerProtocolCutover({
        52,
        "pid:900;start:scheduler-start",
        "/tmp/LSTM_Release",
        "ps_inspection_complete;active_scheduler_dispatch_processes=0"}));
    assert(transaction.exec(
               "SELECT cutover_state FROM experiment_scheduler_protocol "
               "WHERE singleton=true").one_row()[0].as<std::string>() ==
           "complete");

    transaction.exec(R"SQL(
        INSERT INTO experiment(
            experiment_id,symbol,prediction_horizon,c_next_threshold,
            target_epochs,checkpoint_interval,train_start,train_end,
            last_model_id,donchian20_mode,feature_warmup_scope,
            donchian_lookback,feature_ablation_mask,resume_expand_input_width,
            training_objective_canonical,training_objective_hash,
            scheduler_priority,resume_requested,scheduler_resume_origin,
            status,phase,current_epoch,current_operation,worker_control_state,
            started_at,worker_started_at,completed_at,exit_code,error_message,
            updated_at
        ) VALUES
        (30,'transitioninfer',4,0.1,80,20,'2020-01-01','2021-01-01',
         700,'enabled','full_history_warmup','20','none',false,
         'objective','hash','high',false,'none','failed','analyze',40,
         'analyze','running',clock_timestamp(),clock_timestamp(),
         clock_timestamp(),9,'fixture failure',clock_timestamp()),
        (31,'transitiontrain',4,0.1,80,20,'2020-01-01','2021-01-01',
         701,'enabled','full_history_warmup','20','none',false,
         'objective','hash','normal',false,'none','pending','infer',20,
         'infer','running',clock_timestamp(),clock_timestamp(),NULL,NULL,NULL,
         clock_timestamp());
    )SQL");

    const auto transition = repository.loadExperimentTransition(30, true);
    assert(transition);
    assert(transition->experiment.experimentId == 30);
    assert(transition->experiment.lastModelId == 700);
    assert(transition->status == "failed");
    assert(transition->phase == "analyze");
    assert(transition->currentEpoch == 40);
    assert(transition->schedulerPriority == "high");
    assert(!transition->hasAttachedWorkerAttempt);
    assert(repository.applyExperimentTransition({
               ExperimentTransitionAction::RequeueInference,
               30,
               "failed",
               "analyze",
               "high",
               "none",
               "pending",
               "infer",
               std::nullopt}) ==
           ExperimentTransitionPersistenceResult::Updated);
    const pqxx::row requeuedInference = transaction.exec(
        "SELECT status,phase,resume_requested,scheduler_resume_origin,"
        "started_at,worker_started_at,completed_at,exit_code,error_message,"
        "current_operation,operator_forced_final_inference_rerun_requested "
        "FROM experiment WHERE experiment_id=30").one_row();
    assert(requeuedInference[0].as<std::string>() == "pending");
    assert(requeuedInference[1].as<std::string>() == "infer");
    assert(requeuedInference[2].as<bool>());
    assert(requeuedInference[3].as<std::string>() == "operator");
    for (int column = 4; column <= 9; ++column)
        assert(requeuedInference[column].is_null());
    assert(requeuedInference[10].as<bool>());

    const ExperimentTransitionUpdate requeueTraining{
        ExperimentTransitionAction::RequeueTraining,
        31,
        "pending",
        "infer",
        "normal",
        "none",
        "pending",
        "train",
        900};
    assert(repository.applyExperimentTransition(requeueTraining) ==
           ExperimentTransitionPersistenceResult::Updated);
    const pqxx::row requeuedTraining = transaction.exec(
        "SELECT status,phase,current_operation,last_model_id,resume_model_id,"
        "resume_requested,scheduler_resume_origin "
        "FROM experiment WHERE experiment_id=31").one_row();
    assert(requeuedTraining[0].as<std::string>() == "pending");
    assert(requeuedTraining[1].as<std::string>() == "train");
    assert(requeuedTraining[2].as<std::string>() == "train");
    assert(requeuedTraining[3].as<long long>() == 900);
    assert(requeuedTraining[4].as<long long>() == 900);
    assert(!requeuedTraining[5].as<bool>());
    assert(requeuedTraining[6].as<std::string>() == "none");
    assert(repository.applyExperimentTransition(requeueTraining) ==
           ExperimentTransitionPersistenceResult::
               AtomicPreconditionRejected);

    transaction.exec(R"SQL(
        INSERT INTO experiment_checkpoint_eval(
            checkpoint_eval_id,experiment_id,parent_experiment_id,
            checkpoint_epoch,checkpoint_model_id,status,phase,analysis_id,
            updated_at
        ) VALUES(
            206,10,10,30,705,'completed','done',502,clock_timestamp()
        );
        INSERT INTO experiment_analysis_result(
            analysis_id,experiment_id,model_id,symbol,prediction_horizon,
            completed_epochs,infer_accuracy,leader_score,analysis_scope,
            analysis_status,checkpoint_eval_id,checkpoint_epoch,
            parent_experiment_id
        ) VALUES(
            502,10,705,'running',4,30,0.69,0.79,'checkpoint',
            'completed',206,30,10
        );
        INSERT INTO inference_eval_result(
            id,checkpoint_eval_id,inference_scope,status,parent_experiment_id,
            model_id,checkpoint_epoch,symbol,prediction_horizon,
            threshold_logret,from_date,to_date,accuracy
        ) VALUES(
            602,206,'checkpoint','completed',10,705,30,'running',4,
            0.1,'2025-01-01','2025-02-01',0.69
        );
        UPDATE experiment SET status='running',phase='train',current_epoch=20,
            target_epochs=100,checkpoint_policy_min_leader_score=0.90,
            stop_after_checkpoint_epoch=NULL,
            checkpoint_policy_stop_decision_id=NULL,
            active_scheduler_worker_attempt_id=101
        WHERE experiment_id=10;
        UPDATE experiment_scheduler_worker_attempt SET experiment_id=10,
            worker_kind='experiment',lifecycle_phase='train',
            scheduler_invocation_id='scheduler-a',scheduler_fencing_token=7,
            lifecycle_state='running'
        WHERE worker_attempt_id=101;
        UPDATE experiment_scheduler_lease SET
            owner_scheduler_invocation_id='scheduler-a',fencing_token=7,
            authority_state='active',expires_at=clock_timestamp()+interval '1 hour'
        WHERE singleton=true;
    )SQL");
    const CheckpointEvaluationRecord stopPolicyEvaluation{
        206, 10, 705, 30, "running", 4};
    policy = repository.loadCheckpointPolicyForEvaluation(10);
    assert(policy);
    *policy = repository.reconcileCheckpointPolicyIdentity(
        stopPolicyEvaluation, *policy);
    assert(policy->policyRevision == 2);
    const auto stopEvidence =
        repository.loadCheckpointPolicyEvidence(stopPolicyEvaluation);
    assert(stopEvidence.evidence);
    const auto stopContext = PlanCheckpointPolicyDecision(
        stopPolicyEvaluation,
        *policy,
        *stopEvidence.evidence,
        repository.loadCompletedCheckpointPolicyPopulation(10),
        repository.loadCheckpointPolicyRankPopulation(
            stopPolicyEvaluation, *policy));
    assert(stopContext.decision.decision == "stop_requested");
    assert(stopContext.decision.requestedStopEpoch == 40);
    const auto stopIdentity = MakeCheckpointPolicyEvidenceIdentity(
        stopPolicyEvaluation,
        *stopEvidence.evidence,
        stopContext,
        *policy);
    const auto stopDecision = repository.persistCheckpointPolicyDecision(
        stopPolicyEvaluation,
        *policy,
        stopContext.decision,
        *stopEvidence.evidence,
        stopIdentity);
    const std::string stopResult =
        repository.applyCheckpointPolicyStopRequest(
            stopPolicyEvaluation,
            *policy,
            stopContext.decision,
            stopDecision,
            EA::ExperimentScheduler::CheckpointPolicyEvidenceWatermark(
                stopIdentity));
    assert(stopResult == "stop_request_applied");
    const pqxx::row stopped = transaction.exec(
        "SELECT e.stop_after_checkpoint_epoch,"
        "e.checkpoint_policy_stop_decision_id,d.identity_status,"
        "d.stop_request_applied,d.stop_action_worker_attempt_id "
        "FROM experiment e JOIN experiment_checkpoint_decision d "
        "ON d.checkpoint_decision_id=e.checkpoint_policy_stop_decision_id "
        "WHERE e.experiment_id=10;").one_row();
    assert(stopped[0].as<int>() == 40);
    assert(stopped[1].as<long long>() == stopDecision.decisionId);
    assert(stopped[2].as<std::string>() == "action_applied");
    assert(stopped[3].as<bool>());
    assert(stopped[4].as<long long>() == 101);

    transaction.exec(R"SQL(
        CREATE TABLE model(
            model_id bigint PRIMARY KEY,
            experiment_id bigint NOT NULL
        );
        INSERT INTO model(model_id,experiment_id) VALUES(704,10);
        UPDATE experiment SET status='running',phase='infer',last_model_id=704,
            active_scheduler_worker_attempt_id=101
        WHERE experiment_id=10;
        UPDATE experiment_scheduler_worker_attempt SET experiment_id=10,
            checkpoint_eval_id=NULL,worker_kind='experiment',
            lifecycle_phase='infer',capacity_class='infer',
            lifecycle_state='running',reserved_at=clock_timestamp()
        WHERE worker_attempt_id=101;
        INSERT INTO inference_eval_result(
            id,checkpoint_eval_id,inference_scope,status,parent_experiment_id,
            model_id,checkpoint_epoch,symbol,prediction_horizon,
            threshold_logret,from_date,to_date,accuracy,completed_at
        ) VALUES(
            603,NULL,'final','completed',10,704,NULL,'running',4,
            0.1,'2025-01-01','2025-02-01',0.71,clock_timestamp()
        );
    )SQL");
    const auto recovered =
        repository.findAuthoritativeFinalInferenceResultForWorkerAttempt(
            10, 101);
    assert(recovered);
    assert(recovered->resultId == 603);
    assert(recovered->modelId == 704);
    assert(!recovered->forcedFinalInferenceRerun);

    transaction.abort();
    return 0;
}
