#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"; work="$(mktemp -d "${TMPDIR:-/tmp}/ea_scientific_backfill.XXXXXX")"
pgdata="$work/pgdata"; socket="$work/socket"; db="ea_scientific_backfill_${$}"; port="$((56000 + ($$ % 1000)))"; postgres=/opt/homebrew/opt/postgresql@17/bin; binary="$work/backfill-cli"; unit_binary="$work/backfill-unit"; started=false; created=false
trap 's=$?; if $created; then "$postgres/dropdb" -h "$socket" -p "$port" -U pqxx "$db" || true; fi; if $started; then "$postgres/pg_ctl" -D "$pgdata" -m fast -w stop >/dev/null || true; fi; rm -rf "$work"; exit $s' EXIT
mkdir -p "$socket"; "$postgres/initdb" -D "$pgdata" --username=pqxx --auth=trust --no-locale >/dev/null; "$postgres/pg_ctl" -D "$pgdata" -o "-F -k $socket -p $port -h ''" -w start >/dev/null; started=true; "$postgres/createdb" -h "$socket" -p "$port" -U pqxx "$db"; created=true
read -r -a cflags <<< "$(pkg-config --cflags libpqxx)"; read -r -a libs <<< "$(pkg-config --libs libpqxx)"
clang++ -std=c++20 -Wall -Wextra -Werror "${cflags[@]}" -I"$root/Headers" -I"$root/Sources" -I"$root/Sources/SchedulerCore" "$root/Tests/ScientificExecutionProvenanceBackfillCli.cpp" "$root/Sources/SchedulerCore/SemanticWorkerRegistry.cpp" "${libs[@]}" -o "$binary"
clang++ -std=c++20 -Wall -Wextra -Werror "${cflags[@]}" -I"$root/Headers" -I"$root/Sources" -I"$root/Sources/SchedulerCore" "$root/Tests/ScientificExecutionProvenanceBackfillTests.cpp" "$root/Sources/SchedulerCore/SemanticWorkerRegistry.cpp" "${libs[@]}" -o "$unit_binary"
"$unit_binary"
psql=("$postgres/psql" -X -v ON_ERROR_STOP=1 -q -h "$socket" -p "$port" -U pqxx -d "$db")
"${psql[@]}" <<'SQL'
CREATE TABLE experiment (experiment_id bigint PRIMARY KEY);
CREATE TABLE model (model_id bigint PRIMARY KEY, experiment_id bigint NOT NULL REFERENCES experiment, created_at timestamptz NOT NULL, producer_worker_attempt_id bigint);
CREATE TABLE inference_eval_result (id bigint PRIMARY KEY, model_id bigint NOT NULL REFERENCES model, status text NOT NULL, inference_scope text NOT NULL, completed_at timestamptz NOT NULL, producer_worker_attempt_id bigint);
CREATE TABLE experiment_scheduler_worker_attempt (worker_attempt_id bigint PRIMARY KEY,experiment_id bigint NOT NULL REFERENCES experiment,worker_kind text NOT NULL,lifecycle_phase text NOT NULL,capacity_class text NOT NULL,lifecycle_state text NOT NULL,reserved_at timestamptz NOT NULL,completed_at timestamptz,exit_code integer,reconciliation_result text,canonical_executable_path text,semantic_layout_version integer,model_input_width integer,semantic_worker_role text,source_commit text,executable_sha256 text,runtime_identity text,canonical_manifest_path text);
SQL
sql(){ "${psql[@]}" -c "$1"; }; run(){ LSTM_DB_HOST="$socket" LSTM_DB_PORT="$port" LSTM_DB_USER=pqxx LSTM_DB_NAME="$db" "$binary" --backfill-scientific-execution-provenance "$@"; }; reset(){ sql 'TRUNCATE inference_eval_result,model,experiment_scheduler_worker_attempt,experiment; INSERT INTO experiment VALUES (1),(2);'; }; bind(){ "${psql[@]}" -At -c "$1"; }; expect(){ local x="$1"; shift; "$@" >"$work/out"; grep -Fq "$x" "$work/out"; }
train(){ sql "INSERT INTO experiment_scheduler_worker_attempt VALUES ($1,$2,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',NULLIF('$3','NULL')::integer,NULLIF('$4','NULL'),'/retained/train',8,80,'train',repeat('a',40),repeat('b',64),repeat('c',64),'/retained/train/manifest.json');"; }; infer(){ sql "INSERT INTO experiment_scheduler_worker_attempt VALUES ($1,$2,'experiment','infer','infer','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',NULLIF('$3','NULL')::integer,NULLIF('$4','NULL'),'/retained/infer',8,80,'infer',repeat('a',40),repeat('b',64),repeat('c',64),'/retained/infer/manifest.json');"; }; model(){ sql "INSERT INTO model VALUES ($1,$2,'2025-01-01 10:00+00',$3);"; }; result(){ sql "INSERT INTO inference_eval_result VALUES ($1,$2,'completed','final','2025-01-01 10:00+00',$3);"; }
fixture_worker=''
fixture_runtime_dir=''
make_runtime_fixture(){
  local base="$work/Builds/SemanticWorkers" commit="$(printf 'a%.0s' {1..40})" sha runtime default_hash meta_hash
  rm -rf "$work/Builds"; mkdir -p "$base/layout8/$commit"
  mkdir -p "$base/runtime/stage"; printf default >"$base/runtime/stage/default.metallib"; printf metann >"$base/runtime/stage/MetaNN.metallib"
  default_hash="$(shasum -a 256 "$base/runtime/stage/default.metallib" | awk '{print $1}')"; meta_hash="$(shasum -a 256 "$base/runtime/stage/MetaNN.metallib" | awk '{print $1}')"
  printf '{"schema_version":1,"storage":"immutable","resources":[{"built_identity":"MetaNN_metal.metallib","runtime_name":"MetaNN.metallib","sha256":"%s"},{"built_identity":"default.metallib","runtime_name":"default.metallib","sha256":"%s"}]}' "$meta_hash" "$default_hash" >"$base/runtime/stage/manifest.json"
  runtime="$(shasum -a 256 "$base/runtime/stage/manifest.json" | awk '{print $1}')"; mv "$base/runtime/stage" "$base/runtime/$runtime"
  mkdir -p "$base/layout8/$commit/stage"; printf worker >"$base/layout8/$commit/stage/LSTM_Release"; sha="$(shasum -a 256 "$base/layout8/$commit/stage/LSTM_Release" | awk '{print $1}')"; mv "$base/layout8/$commit/stage" "$base/layout8/$commit/$sha"
  printf '{"semantic_layout":8,"model_input_width":80,"source_commit":"%s","sha256":"%s","executable_identity":"LSTM_Release","storage":"immutable"}' "$commit" "$sha" >"$base/layout8/$commit/$sha/manifest.json"
  ln -s "../../../runtime/$runtime/default.metallib" "$base/layout8/$commit/$sha/default.metallib"; ln -s "../../../runtime/$runtime/MetaNN.metallib" "$base/layout8/$commit/$sha/MetaNN.metallib"
  fixture_worker="$base/layout8/$commit/$sha/LSTM_Release"
  fixture_runtime_dir="$base/runtime/$runtime"
}
# A/B/C: dry-run writes neither identity nor producer; apply completes both;
# repeating apply is idempotent.
reset; model 10 1 NULL; train 100 1 0 NULL; expect 'outcome=PROPOSED,artifact_type=model,artifact_id=10' run --dry-run; [[ "$(bind 'SELECT producer_worker_attempt_id IS NULL AND runtime_identity IS NOT NULL FROM model JOIN experiment_scheduler_worker_attempt ON worker_attempt_id=100 WHERE model_id=10')" == t ]]; expect 'writes=1' run --apply --yes; [[ "$(bind 'SELECT producer_worker_attempt_id FROM model WHERE model_id=10')" == 100 ]]; expect 'writes=0' run --apply --yes
# Ambiguous, missing, failed attempts ignored, wrong experiment ignored;
# generic recovered terminal success is valid for train and infer, while the
# historical completed-result recovery is infer-only.
reset; model 11 1 NULL; train 101 1 0 NULL; train 102 1 0 NULL; expect 'outcome=AMBIGUOUS,artifact_type=model,artifact_id=11' run --dry-run
reset; model 12 1 NULL; expect 'outcome=MISSING,artifact_type=model,artifact_id=12' run --dry-run
reset; model 13 1 NULL; train 103 1 1 NULL; train 104 2 0 NULL; expect 'outcome=MISSING,artifact_type=model,artifact_id=13' run --dry-run
reset; model 14 1 NULL; train 105 1 NULL process_missing_result_recovered; expect 'outcome=PROPOSED,artifact_type=model,artifact_id=14' run --dry-run
reset; model 15 1 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (106,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',NULL,'historical_completed_inference_result_recovered',NULL,8,80,'train',repeat('a',40),repeat('b',64),repeat('c',64),NULL);"; expect 'outcome=MISSING,artifact_type=model,artifact_id=15' run --dry-run
# Final inference unique, ambiguous, missing, failed ignored, historical recovered success allowed.
reset; model 20 1 NULL; result 200 20 NULL; infer 201 1 0 NULL; expect 'outcome=PROPOSED,artifact_type=final_inference,artifact_id=200' run --dry-run; expect 'writes=1' run --apply --yes; [[ "$(bind 'SELECT producer_worker_attempt_id FROM inference_eval_result WHERE id=200')" == 201 ]]
reset; model 21 1 NULL; result 210 21 NULL; infer 211 1 0 NULL; infer 212 1 0 NULL; expect 'outcome=AMBIGUOUS,artifact_type=final_inference,artifact_id=210' run --dry-run
reset; model 22 1 NULL; result 220 22 NULL; expect 'outcome=MISSING,artifact_type=final_inference,artifact_id=220' run --dry-run
reset; model 23 1 NULL; result 230 23 NULL; infer 231 1 1 NULL; infer 232 1 NULL historical_completed_inference_result_recovered; expect 'outcome=PROPOSED,artifact_type=final_inference,artifact_id=230' run --dry-run
# Bad path/identity and wrong kind/phase/capacity fail closed; an existing binding is never replaced.
reset; model 30 1 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (301,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'/tmp/not-SemanticWorkers',NULL,NULL,NULL,NULL,NULL,NULL,NULL);"; expect 'outcome=UNRESOLVED_IDENTITY,artifact_type=model,artifact_id=30' run --dry-run
reset; model 31 1 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (311,1,'checkpoint_infer','infer','infer','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,NULL,8,80,'infer',repeat('a',40),repeat('b',64),repeat('c',64),NULL);"; expect 'outcome=MISSING,artifact_type=model,artifact_id=31' run --dry-run
reset; model 32 1 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (321,1,'experiment','infer','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,NULL,8,80,'train',repeat('a',40),repeat('b',64),repeat('c',64),NULL);"; expect 'outcome=MISSING,artifact_type=model,artifact_id=32' run --dry-run
reset; model 40 1 401; train 401 1 0 NULL; train 402 1 0 NULL; expect 'outcome=ALREADY_BOUND,artifact_type=model,artifact_id=40' run --dry-run; [[ "$(bind 'SELECT producer_worker_attempt_id FROM model WHERE model_id=40')" == 401 ]]
reset; model 41 1 411; train 411 1 0 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (412,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'/tmp/not-SemanticWorkers',NULL,NULL,NULL,NULL,NULL,NULL,NULL);"; expect 'outcome=ALREADY_BOUND,artifact_type=model,artifact_id=41' run --dry-run
reset; model 42 1 421; train 421 1 0 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (422,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'/tmp/not-SemanticWorkers',8,80,'train',repeat('a',40),repeat('b',64),repeat('c',64),'/retained/train/manifest.json');"; expect 'outcome=ALREADY_BOUND,artifact_type=model,artifact_id=42' run --dry-run
reset; model 43 1 431; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (431,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'/tmp/not-SemanticWorkers',NULL,NULL,NULL,NULL,NULL,NULL,NULL);"; expect 'outcome=CONFLICT,artifact_type=model,artifact_id=43' run --dry-run
reset; model 44 1 999; train 441 1 0 NULL; expect 'outcome=CONFLICT,artifact_type=model,artifact_id=44' run --dry-run
# Identity precedence uses retained repository packages. Registry wins over
# conflicting partial persisted metadata; an unregistered immutable package
# falls through to validated content-addressed-path recovery.
registry_train="$root/Builds/SemanticWorkers/layout8/3ba4844a41dc75ec21397ceadb02802ff45743b4/b8282bff6cc07c79ff2c07ae7584bd2e1d93a48a457141897ad4d2c219a8c392/LSTM_Release"
legacy_train="$root/Builds/SemanticWorkers/layout7/c38838c2311b3984ac7f2c4c5663c10deb6cbf6a/a770f1beca659e52df95762e73e247101280468c4b1d7182f125a5338599f237/LSTM_Release"
reset; model 50 1 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (501,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'$registry_train',NULL,NULL,NULL,NULL,NULL,NULL,NULL);"; expect 'identity_provenance=registry' run --dry-run; [[ "$(bind 'SELECT semantic_layout_version IS NULL AND model_input_width IS NULL AND runtime_identity IS NULL FROM experiment_scheduler_worker_attempt WHERE worker_attempt_id=501')" == t ]]; [[ "$(bind 'SELECT producer_worker_attempt_id IS NULL FROM model WHERE model_id=50')" == t ]]; expect 'writes=1' run --apply --yes; [[ "$(bind "SELECT semantic_layout_version=8 AND model_input_width=80 AND semantic_worker_role='train' AND source_commit='3ba4844a41dc75ec21397ceadb02802ff45743b4' AND executable_sha256='b8282bff6cc07c79ff2c07ae7584bd2e1d93a48a457141897ad4d2c219a8c392' AND runtime_identity IS NOT NULL AND canonical_manifest_path IS NOT NULL FROM experiment_scheduler_worker_attempt WHERE worker_attempt_id=501")" == t ]]; [[ "$(bind 'SELECT producer_worker_attempt_id FROM model WHERE model_id=50')" == 501 ]]
# D: matching partial attempt identity is completed, never overwritten.
reset; model 51 1 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (511,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'$registry_train',8,NULL,NULL,NULL,NULL,NULL,NULL);"; expect 'writes=1' run --apply --yes; [[ "$(bind "SELECT semantic_layout_version=8 AND model_input_width=80 AND semantic_worker_role='train' AND producer_worker_attempt_id=511 FROM experiment_scheduler_worker_attempt JOIN model ON model_id=51 WHERE worker_attempt_id=511")" == t ]]
# E/F: partial or complete conflicting retained fields fail closed and leave
# both the attempt and artifact untouched.
reset; model 54 1 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (541,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'$registry_train',7,NULL,NULL,NULL,NULL,NULL,NULL);"; expect 'outcome=CONFLICT,artifact_type=model,artifact_id=54' run --apply --yes; [[ "$(bind 'SELECT semantic_layout_version=7 AND producer_worker_attempt_id IS NULL FROM experiment_scheduler_worker_attempt JOIN model ON model_id=54 WHERE worker_attempt_id=541')" == t ]]
reset; model 545 1 5451; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (5451,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'$registry_train',7,NULL,NULL,NULL,NULL,NULL,NULL);"; expect 'outcome=CONFLICT,artifact_type=model,artifact_id=545' run --dry-run
reset; model 546 1 5461; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (5461,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'$registry_train',NULL,NULL,NULL,NULL,NULL,NULL,NULL),(5462,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'$registry_train',7,NULL,NULL,NULL,NULL,NULL,NULL);"; expect 'outcome=ALREADY_BOUND,artifact_type=model,artifact_id=546' run --dry-run
reset; model 55 1 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (551,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'$registry_train',7,70,'infer',repeat('d',40),repeat('e',64),repeat('f',64),'/conflict');"; expect 'outcome=CONFLICT,artifact_type=model,artifact_id=55' run --apply --yes; [[ "$(bind "SELECT semantic_layout_version=7 AND model_input_width=70 AND semantic_worker_role='infer' AND source_commit=repeat('d',40) AND producer_worker_attempt_id IS NULL FROM experiment_scheduler_worker_attempt JOIN model ON model_id=55 WHERE worker_attempt_id=551")" == t ]]
# G: an existing producer FK is immutable and is never replaced.
reset; model 56 1 561; train 561 1 0 NULL; train 562 1 0 NULL; expect 'outcome=ALREADY_BOUND,artifact_type=model,artifact_id=56' run --apply --yes; [[ "$(bind 'SELECT producer_worker_attempt_id FROM model WHERE model_id=56')" == 561 ]]
reset; model 52 1 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (521,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'$legacy_train',NULL,NULL,NULL,NULL,NULL,NULL,NULL);"; expect 'outcome=UNRESOLVED_IDENTITY,artifact_type=model,artifact_id=52' run --dry-run
reset; model 53 1 NULL; result 530 53 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (531,1,'experiment','infer','infer','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'$registry_train',NULL,NULL,NULL,NULL,NULL,NULL,NULL);"; expect 'outcome=UNRESOLVED_IDENTITY,artifact_type=final_inference,artifact_id=530' run --dry-run
# The publisher's two exact worker-package-local runtime links are the only
# accepted historical runtime association.  Every rejection is independent.
make_runtime_fixture; reset; model 60 1 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (601,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'$fixture_worker',NULL,NULL,NULL,NULL,NULL,NULL,NULL);"; expect 'identity_provenance=validated_semanticworkers_path' run --dry-run --semantic-worker-registry="$work/missing-registry.json"
# A single valid retained runtime package is not an executable-to-runtime
# relationship.  With both package-local publication links absent, legacy
# path/manifest/SHA evidence remains unresolved.
make_runtime_fixture; rm "$(dirname "$fixture_worker")/default.metallib" "$(dirname "$fixture_worker")/MetaNN.metallib"; reset; model 61 1 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (611,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'$fixture_worker',NULL,NULL,NULL,NULL,NULL,NULL,NULL);"; expect 'outcome=UNRESOLVED_IDENTITY,artifact_type=model,artifact_id=61' run --dry-run --semantic-worker-registry="$work/missing-registry.json"
make_runtime_fixture; rm "$(dirname "$fixture_worker")/default.metallib"; ln -s /tmp "$(dirname "$fixture_worker")/default.metallib"; reset; model 62 1 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (621,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'$fixture_worker',NULL,NULL,NULL,NULL,NULL,NULL,NULL);"; expect 'outcome=UNRESOLVED_IDENTITY,artifact_type=model,artifact_id=62' run --dry-run --semantic-worker-registry="$work/missing-registry.json"
make_runtime_fixture; mv "$fixture_runtime_dir" "$(dirname "$fixture_runtime_dir")/not-a-runtime-identity"; reset; model 63 1 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (631,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'$fixture_worker',NULL,NULL,NULL,NULL,NULL,NULL,NULL);"; expect 'outcome=UNRESOLVED_IDENTITY,artifact_type=model,artifact_id=63' run --dry-run --semantic-worker-registry="$work/missing-registry.json"
make_runtime_fixture; rm "$fixture_runtime_dir/manifest.json"; reset; model 64 1 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (641,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'$fixture_worker',NULL,NULL,NULL,NULL,NULL,NULL,NULL);"; expect 'outcome=UNRESOLVED_IDENTITY,artifact_type=model,artifact_id=64' run --dry-run --semantic-worker-registry="$work/missing-registry.json"
make_runtime_fixture; printf '{}' >"$fixture_runtime_dir/manifest.json"; reset; model 65 1 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (651,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'$fixture_worker',NULL,NULL,NULL,NULL,NULL,NULL,NULL);"; expect 'outcome=UNRESOLVED_IDENTITY,artifact_type=model,artifact_id=65' run --dry-run --semantic-worker-registry="$work/missing-registry.json"
make_runtime_fixture; rm "$(dirname "$fixture_worker")/default.metallib"; ln -s ../../../../../../etc/passwd "$(dirname "$fixture_worker")/default.metallib"; reset; model 66 1 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (661,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'$fixture_worker',NULL,NULL,NULL,NULL,NULL,NULL,NULL);"; expect 'outcome=UNRESOLVED_IDENTITY,artifact_type=model,artifact_id=66' run --dry-run --semantic-worker-registry="$work/missing-registry.json"
# H: a binding failure rolls back the preceding NULL-only identity completion.
reset; model 67 1 NULL; sql "INSERT INTO experiment_scheduler_worker_attempt VALUES (671,1,'experiment','train','train','completed','2025-01-01 09:00+00','2025-01-01 11:00+00',0,NULL,'$registry_train',NULL,NULL,NULL,NULL,NULL,NULL,NULL);"; sql "CREATE FUNCTION reject_model_producer_binding() RETURNS trigger LANGUAGE plpgsql AS \$\$ BEGIN RAISE EXCEPTION 'reject producer binding'; END \$\$; CREATE TRIGGER reject_model_producer_binding BEFORE UPDATE OF producer_worker_attempt_id ON model FOR EACH ROW WHEN (NEW.producer_worker_attempt_id IS NOT NULL) EXECUTE FUNCTION reject_model_producer_binding();"; run --apply --yes >"$work/failing-apply.out" 2>&1 || true; [[ "$(bind 'SELECT semantic_layout_version IS NULL AND model_input_width IS NULL AND runtime_identity IS NULL FROM experiment_scheduler_worker_attempt WHERE worker_attempt_id=671')" == t ]]; [[ "$(bind 'SELECT producer_worker_attempt_id IS NULL FROM model WHERE model_id=67')" == t ]]
echo SCIENTIFIC_EXECUTION_PROVENANCE_BACKFILL_DISPOSABLE_TESTS=passed
