#!/usr/bin/env python3
"""Generate the AI-facing ExpertAdvisor repository reference."""
from __future__ import annotations
import argparse, json, re, sys
from pathlib import Path

class ReferenceError(RuntimeError): pass

def match(text, pattern, name):
    m = re.search(pattern, text, re.MULTILINE)
    if not m: raise ReferenceError(f"unable to extract {name}")
    return m

def facts(repo: Path):
    expansion=(repo/"Headers/ModelInputExpansion.hpp").read_text()
    contract=(repo/"Headers/ModelInputContract.hpp").read_text()
    layout=int(match(expansion,r"kModelInputSemanticLayoutVersion\s*=\s*(\d+)\s*;","current layout").group(1))
    returns=int(match(contract,r"kModelReturnFeatureCount\s*=\s*(\d+)\s*;","return feature count").group(1))
    block=match(
        expansion,
        r"kModelInputSemanticLayoutRegistry\s*\{\{([\s\S]*?)\}\}\s*;",
        "layout registry",
    ).group(1)
    chain=[(int(a),b.strip(),int(c)) for a,b,c in re.findall(r"\{\s*(\d+)\s*,\s*([^,{}]+?)\s*,\s*(\d+)\s*\}",block)]
    if not chain or chain[-1][0]!=layout: raise ReferenceError("layout registry tail mismatch")
    reg=json.loads((repo/"Builds/SemanticWorkers/registry.json").read_text())
    if reg.get("current_layout")!=layout:
        raise ReferenceError(f"semantic layout mismatch: C++={layout}, registry={reg.get('current_layout')}")
    workers=[w for w in reg["workers"] if w.get("worker_rule")=="current" and w.get("semantic_layout")==layout]
    if sorted(w.get("worker_role") for w in workers)!=["infer","train"]:
        raise ReferenceError("current layout must have exactly one train and one infer worker")
    widths={w.get("model_input_width") for w in workers}
    if len(widths)!=1: raise ReferenceError("current workers disagree on model input width")
    width=next(iter(widths))
    tail=chain[-1][1]
    expr=match(contract,r"kCurrentModelInputWidth\s*=\s*([^;]+)\s*;","current width expression").group(1).strip()
    if expr!=tail: raise ReferenceError("current width expression does not match layout registry tail")
    numeric=re.search(rf"static_assert\(\s*{re.escape(tail)}\s*==\s*(\d+)\s*\)",contract)
    if numeric and int(numeric.group(1))!=width:
        raise ReferenceError("worker width disagrees with C++ width assertion")
    return layout,returns,width,chain,reg,sorted(workers,key=lambda w:w["worker_role"])

def render(repo: Path):
    layout,returns,width,chain,reg,workers=facts(repo)
    L=["# ExpertAdvisor AI Reference","",
       "<!-- Generated by Scripts/GenerateExpertAdvisorReference.py; do not edit. -->","",
       "This compact reference orients AI-assisted development. It is generated from checked-in",
       "repository sources and is not an independent source of architectural authority.","",
       "## Generated current facts","",
       f"- Current model-input semantic layout: `{layout}`.",
       f"- Current model input width: `{width}`.",
       f"- Current Tensor feature width: `{width-returns}`.",
       f"- Model return-feature suffix width: `{returns}`.",
       f"- Semantic-worker registry schema: `{reg['schema_version']}`.",
       f"- Semantic-worker registry current layout: `{reg['current_layout']}`.","",
       "### Current published semantic workers","",
       "| Role | Layout | Width | Capabilities | Source commit | SHA-256 | Executable |",
       "|---|---:|---:|---|---|---|---|"]
    for w in workers:
        caps=", ".join(f"`{x}`" for x in w.get("capabilities",[]))
        L.append(f"| `{w['worker_role']}` | {w['semantic_layout']} | {w['model_input_width']} | {caps} | `{w['source_commit']}` | `{w['sha256']}` | `Builds/SemanticWorkers/{w['executable']}` |")
    L += ["","### Registered semantic-layout chain","","| Layout | Maximum-width constant | Predecessor |","|---:|---|---:|"]
    for a,b,c in chain: L.append(f"| {a} | `{b}` | {c} |")
    L += ["","## Architectural invariants","",
      "Generated facts above may change. The rules below are durable orientation rules; authoritative",
      "definitions remain in the cited repository sources.","",
      "- PostgreSQL is the durable source of truth. Never invent database column names; consult `Database/LSTM_schema.sql`.",
      "- Experiment semantic identity uses deterministic canonical content.",
      "- Historical semantic layouts and persisted identities are compatibility contracts; do not rewrite them because a newer layout is current.",
      "- Scheduler and semantic-worker identities are separate. Model-bearing work is routed through the validated semantic-worker registry by persisted layout, width, role, and capability.",
      "- Published semantic workers are immutable artifacts identified by source commit and SHA-256; do not replace an artifact in place.",
      "- Feature-ablation expressions must be resolved against the experiment semantic layout.",
      "- Recommendation/campaign evidence does not implicitly grant execution authority; preserve accepted ADR ownership and authorization boundaries.",
      "- Treat phase/review outputs as historical evidence. Historical PIDs, git status, and current-layout statements are not automatically current state.",
      "- Commit implementation changes before a qualifying product build so retained build provenance names committed source.","",
      "## Authority map","",
      "| Subject | Start here |","|---|---|",
      "| Architecture | `docs/architecture/README.md` |",
      "| Governing decisions | `docs/architecture/adr/README.md` |",
      "| Model architecture | `docs/architecture/Volume_IV_Model_Architecture.md` |",
      "| Training | `docs/architecture/Volume_V_Training_Engine.md` |",
      "| Inference/evaluation | `docs/architecture/Volume_VI_Inference_Evaluation.md` |",
      "| Experiment lifecycle | `docs/architecture/Volume_VII_Experiment_Lifecycle.md` |",
      "| Profitability | `docs/architecture/Volume_IX_Trading_Profitability.md` |",
      "| Scheduler | `docs/architecture/Volume_XI_Scheduler.md` |",
      "| Database | `docs/architecture/Volume_XII_Database.md` |",
      "| Physical schema | `Database/LSTM_schema.sql` |",
      "| Model-input contract | `Headers/ModelInputContract.hpp` |",
      "| Semantic layout/expansion | `Headers/ModelInputExpansion.hpp` |",
      "| Tensor columns | `Headers/FeatureLayout.hpp` |",
      "| Market structures | `Headers/MarketStructureRegistry.hpp` |",
      "| Feature ablation | `Headers/FeatureAblation.hpp` |",
      "| Semantic workers | `Builds/SemanticWorkers/registry.json` |","",
      "## AI-assisted development boundary","",
      "This reference is an orientation and correctness aid. It does not authorize mutation of the",
      "production database, experiment queue/requeue, worker signaling, artifact publication/replacement,",
      "semantic-layout changes, or production cutover. Normal operator, architecture, provenance, test,",
      "and commit/build controls remain authoritative.","",
      "If this reference conflicts with an authoritative source, resolve the discrepancy from the authoritative source.",""]
    return "\n".join(L)

def main():
    p=argparse.ArgumentParser()
    p.add_argument("--repo-root",type=Path,default=Path(__file__).resolve().parents[1])
    p.add_argument("--output",type=Path)
    p.add_argument("--check",action="store_true")
    a=p.parse_args(); repo=a.repo_root.resolve(); out=a.output or repo/"docs/ai/ExpertAdvisorReference.md"
    try: content=render(repo)
    except (OSError,KeyError,json.JSONDecodeError,ReferenceError) as e:
        print(f"GenerateExpertAdvisorReference: {e}",file=sys.stderr); return 1
    if a.check:
        try: old=out.read_text()
        except OSError as e: print(f"GenerateExpertAdvisorReference: {e}",file=sys.stderr); return 1
        if old!=content:
            print("GenerateExpertAdvisorReference: committed reference is stale; regenerate it",file=sys.stderr); return 1
        print("ExpertAdvisorReference is current"); return 0
    out.parent.mkdir(parents=True,exist_ok=True); out.write_text(content)
    print(f"wrote {out}"); return 0
if __name__=="__main__": raise SystemExit(main())
