#!/usr/bin/env python3
"""Generate the source provenance embedded in an ExpertAdvisor build.

Release provenance is authorizable only when the explicitly supplied
repository is a clean Git checkout.  Debug builds receive an unavailable
provenance marker because the C++ production-admission boundary is already
fail-closed for non-NDEBUG builds.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import subprocess
import tempfile


COMMIT_PATTERN = re.compile(r"[0-9a-f]{40}\Z")


def git_output(repository_root: Path, *arguments: str) -> str:
    result = subprocess.run(
        ["/usr/bin/git", "-C", str(repository_root), *arguments],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return result.stdout.rstrip("\r\n")


def release_commit(repository_root: Path) -> str:
    if not (repository_root / ".git").exists():
        raise RuntimeError("repository root does not contain .git")
    status = git_output(repository_root, "status", "--porcelain")
    if status:
        raise RuntimeError("Release provenance requires a clean source tree")
    commit = git_output(repository_root, "rev-parse", "--verify", "HEAD")
    if not COMMIT_PATTERN.fullmatch(commit):
        raise RuntimeError("HEAD is not an exact lowercase 40-hex commit")
    return commit


def header_text(commit: str) -> str:
    return (
        "// Generated by Scripts/GenerateBuildProvenance.py; do not edit.\n"
        "#pragma once\n"
        f'#define EXPERTADVISOR_SOURCE_COMMIT "{commit}"\n'
    )


def write_atomically(output: Path, content: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=output.parent,
            prefix=f".{output.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary:
            temporary.write(content)
            temporary.flush()
            os.fsync(temporary.fileno())
            temporary_name = temporary.name
        os.replace(temporary_name, output)
        temporary_name = None
    finally:
        if temporary_name is not None:
            try:
                os.unlink(temporary_name)
            except FileNotFoundError:
                pass


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repository-root", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--configuration", required=True)
    return parser.parse_args()


def main() -> int:
    arguments = parse_arguments()
    if arguments.configuration == "Release":
        commit = release_commit(arguments.repository_root.resolve())
    else:
        commit = ""
    write_atomically(arguments.output.resolve(), header_text(commit))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except RuntimeError as error:
        raise SystemExit(f"GenerateBuildProvenance.py: {error}")
